### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by BugGreedy** [BugGreedy/furima-29213#12]
# URL
https://furima-29213.herokuapp.com/
# Basic認証
id:admin
pass:2222
# 出品者用のメールアドレスとパスワード
mail : shuppin@shuppin.jp
pass : sample6
# 購入者用のメールアドレスとパスワード
mail : kounyuu@kounyuu.jp
pass : sample6
# 購入用カードの番号・期限・セキュリティコード
No: 4242424242424242
M/Y：12/23
CVC: 123

**Comment by rumaruma0408** [comment]
BugGreedyさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by BugGreedy** [comment]
レビューありがとうございます。
早急にご確認いただきありがとうございます。
